---
- name: Install Kafka and Zookeeper on EC2
  hosts: kafka
  become: yes
  vars:
    kafka_version: "3.7.2"
    scala_version: "2.12"
    kafka_tgz_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    kafka_dir: "/opt/kafka_{{ scala_version }}-{{ kafka_version }}"
    kafka_symlink: "/opt/kafka"

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-11-jdk
        - wget

    - name: Download Kafka
      get_url:
        url: "{{ kafka_tgz_url }}"
        dest: /opt/kafka.tgz

    - name: Extract Kafka
      unarchive:
        src: /opt/kafka.tgz
        dest: /opt
        remote_src: yes

    - name: Create symbolic link for Kafka
      file:
        src: "{{ kafka_dir }}"
        dest: "{{ kafka_symlink }}"
        state: link
        force: yes

    - name: Start Zookeeper
      shell: "{{ kafka_symlink }}/bin/zookeeper-server-start.sh -daemon {{ kafka_symlink }}/config/zookeeper.properties"

    - name: Wait for Zookeeper
      wait_for:
        host: 127.0.0.1
        port: 2181
        timeout: 60

    - name: Start Kafka Broker
      shell: "{{ kafka_symlink }}/bin/kafka-server-start.sh -daemon {{ kafka_symlink }}/config/server.properties"
