name: Provision EC2 and Install Kafka

on:
  workflow_dispatch:

jobs:
  provision-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip ansible openssh-client
          curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install terraform -y

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Terraform Init and Apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve -no-color | tee apply_output.txt
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "$PUBLIC_IP" > ../amsible/ec2_ip.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: SSH Host Scan
        run: |
          ssh-keyscan -H $PUBLIC_IP >> ~/.ssh/known_hosts

      - name: Create Inventory File
        run: |
          mkdir -p amsible/inventory
          echo "[kafka]" > amsible/inventory/hosts.ini
          echo "$PUBLIC_IP" >> amsible/inventory/hosts.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i amsible/inventory/hosts.ini amsible/playbook.yml
